'use strict';
(() => {
const TEXT={
 ar:{title:'اختر شخصيتك',instruction:'اضغط على الولد أو البنت.',greeting:'أهلاً بك! هيا نبدأ',boy:'الولد',girl:'البنت',pickBoy:'اختيار الولد',pickGirl:'اختيار البنت',hint:'اختر شخصيتك لنبدأ المغامرة.',name:'ما اسمك؟',start:'ابدأ اللعب',required:'اكتب اسمك أولًا.',invalid:'استخدم اسمًا دون رموز خاصة.',selected:'تم اختيار',ready:'أنت جاهز يا {name}!',readyGuest:'أنت جاهز! هيا نبدأ',detail:'تنتهي المعاينة هنا. الانتقال إلى الحيّ يأتي في التصميم التالي.',edit:'العودة',storage:'الحفظ غير متاح الآن. يبقى اختيارك خلال هذه الزيارة.',returnTitle:'أهلاً بعودتك!',returnHint:'مغامرتك تنتظرك.',resume:'أهلاً {name} — تابع اللعب',resumeGuest:'أهلاً بك — تابع اللعب',change:'تغيير الشخصية',mute:'كتم الصوت',unmute:'تشغيل الصوت'},
 de:{title:'Wähle deine Figur',instruction:'Tippe auf den Jungen oder das Mädchen.',greeting:'Hallo! Los geht’s',boy:'Junge',girl:'Mädchen',pickBoy:'Junge auswählen',pickGirl:'Mädchen auswählen',hint:'Wähle deine Figur für dein Abenteuer.',name:'Wie heißt du?',start:'Los geht’s',required:'Bitte gib deinen Namen ein.',invalid:'Bitte verwende einen Namen ohne Sonderzeichen.',selected:'Ausgewählt',ready:'Bereit, {name}!',readyGuest:'Bereit? Los geht’s!',detail:'Die Vorschau endet hier. Das Viertel folgt im nächsten Entwurf.',edit:'Zurück',storage:'Speichern ist gerade nicht möglich. Deine Auswahl bleibt für diesen Besuch erhalten.',returnTitle:'Willkommen zurück!',returnHint:'Dein Abenteuer wartet auf dich.',resume:'Hallo {name} — weiterspielen',resumeGuest:'Willkommen — weiterspielen',change:'Figur ändern',mute:'Ton ausschalten',unmute:'Ton einschalten'},
 en:{title:'Choose your character',instruction:'Tap the boy or the girl.',greeting:'Hello! Let’s begin',boy:'Boy',girl:'Girl',pickBoy:'Choose the boy',pickGirl:'Choose the girl',hint:'Choose your character to begin.',name:'What’s your name?',start:'Let’s play',required:'Enter your name first.',invalid:'Please use a name without special symbols.',selected:'Selected',ready:'Ready, {name}!',readyGuest:'Ready? Let’s begin!',detail:'This preview ends here. The neighbourhood comes in the next design.',edit:'Back',storage:'Saving is unavailable right now. Your selection stays for this visit.',returnTitle:'Welcome back!',returnHint:'Your adventure is waiting.',resume:'Hello {name} — continue playing',resumeGuest:'Welcome — continue playing',change:'Change character',mute:'Mute sound',unmute:'Turn sound on'}
};
const $=id=>document.getElementById(id);
const PROFILE='hudhud-home-profile-v1',SETTINGS='hudhud-home-settings-v1';
const PREVIEW=document.body.dataset.previewState==='returning';
let language='de',character=null,saved=null,storageOK=true,muted=true,audio=null,errorKey='',progress=null;
const cleanName=value=>value.normalize('NFC').replace(/[\u0000-\u001f\u007f\u200b-\u200f\u202a-\u202e\u2066-\u2069]/g,'').trim().replace(/\s+/g,' ');
const validName=value=>value.length<=24&&(!value||/^[\p{L}\p{M}\p{N} .’'\-]+$/u.test(value));
function read(key){try{return JSON.parse(localStorage.getItem(key)||'null');}catch{storageOK=false;return null;}}
const raw=read(PROFILE),prefs=read(SETTINGS),legacy=read('hudhud-aq01-v1'),world=read('hudhud-mobile-world-v1');
if(raw&&TEXT[raw.language])language=raw.language;
if(prefs&&TEXT[prefs.language])language=prefs.language;
if(typeof prefs?.muted==='boolean')muted=prefs.muted;
if(raw&&['boy','girl'].includes(raw.character)&&typeof raw.name==='string'&&validName(cleanName(raw.name))){saved={...raw,name:cleanName(raw.name)};character=saved.character;$('player-name').value=saved.name;}
if(world&&(world.visited||((Array.isArray(world.completedSteps)&&world.completedSteps.length>0)||(Array.isArray(world.completedStages)&&world.completedStages.length>0))))progress={source:'world',value:world};
else if(legacy&&Number.isInteger(legacy.step)&&legacy.step>0&&legacy.step<=8)progress={source:'legacy',value:legacy};
if(PREVIEW){language='ar';saved={version:1,character:'girl',name:'سارة',language:'ar'};character='girl';$('player-name').value=saved.name;progress={source:'preview',value:{completedSteps:['example']}};muted=true;}
const t=()=>TEXT[language];
function write(key,value){if(PREVIEW)return;try{localStorage.setItem(key,JSON.stringify(value));}catch{storageOK=false;}$('storage-note').hidden=storageOK;$('storage-note').textContent=t().storage;}
function saveSettings(){write(SETTINGS,{language,muted});}
function ping(){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(580,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(780,audio.currentTime+.07);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.11);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.12);}catch{}}
function updateMute(){$('mute').setAttribute('aria-pressed',String(muted));$('mute').setAttribute('aria-label',t()[muted?'unmute':'mute']);}
function select(next,announce=true){character=next;$('selection-screen').classList.add('has-selection');document.querySelectorAll('[data-character]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.character===character)));$('profile-form').hidden=false;$('selection-hint').hidden=true;if(announce){$('selection-status').textContent=t().selected+' '+t()[next];ping();}}
function translate(){const c=t();document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.title='HUDHUD — '+c.title;for(const [id,key] of Object.entries({'welcome-title':'title','instruction':'instruction','greeting':'greeting','boy-label':'boy','girl-label':'girl','selection-hint':'hint','start':'start','edit-profile':'edit','ready-detail':'detail','storage-note':'storage','returning-title':'returnTitle','returning-hint':'returnHint','change-character':'change'}))$(id).textContent=c[key];$('name-label').textContent=c.name;document.querySelector('[data-character=boy]').setAttribute('aria-label',c.pickBoy);document.querySelector('[data-character=girl]').setAttribute('aria-label',c.pickGirl);document.querySelectorAll('[data-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lang===language)));$('continue').textContent=saved?.name?c.resume.replace('{name}',saved.name):c.resumeGuest;$('error').textContent=errorKey?c[errorKey]:'';$('storage-note').hidden=storageOK;updateMute();}
function showSelection(){$('returning-screen').hidden=true;$('selection-screen').hidden=false;if(character)select(character,false);translate();}
function showReturning(){$('returning-screen').classList.toggle('no-avatar',!character);document.querySelector('.returning-figure').hidden=!character;$('selection-screen').hidden=true;$('returning-screen').hidden=false;$('returning-portrait').src=document.querySelector('[data-character="'+(character==='boy'?'boy':'girl')+'"] .portrait').src;translate();}
function ready(isReturning){if(!saved?.name){showSelection();$('player-name').focus();return;}const name=saved.name;$('ready-title').textContent=name?t().ready.replace('{name}',name):t().readyGuest;if(document.body.dataset.connectedWorld!=='true')$('ready-dialog').showModal();window.dispatchEvent(new CustomEvent(isReturning?'hudhud:resume':'hudhud:profile-ready',{detail:{...saved,language,muted,progress:progress?.value||null,preview:PREVIEW}}));}
function submit(){if(!character)return;const name=cleanName($('player-name').value);errorKey=!name?'required':validName(name)?'':'invalid';if(errorKey){$('error').textContent=t()[errorKey];$('player-name').setAttribute('aria-invalid','true');$('player-name').focus();return;}$('error').textContent='';$('player-name').removeAttribute('aria-invalid');$('player-name').value=name;saved={version:1,name,character,language};write(PROFILE,saved);saveSettings();ping();ready(false);}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{language=button.dataset.lang;translate();saveSettings();}));
document.querySelectorAll('[data-character]').forEach(button=>button.addEventListener('click',()=>select(button.dataset.character)));
$('player-name').addEventListener('input',()=>{errorKey='';$('error').textContent='';$('player-name').removeAttribute('aria-invalid');});
$('profile-form').addEventListener('submit',event=>{event.preventDefault();submit();});
$('mute').addEventListener('click',()=>{muted=!muted;if(muted&&audio)audio.suspend();updateMute();saveSettings();if(!muted)ping();});
$('continue').addEventListener('click',()=>{ping();ready(true);});$('change-character').addEventListener('click',showSelection);$('edit-profile').addEventListener('click',()=>$('ready-dialog').close());
document.querySelector('.brand').addEventListener('click',event=>{event.preventDefault();if(progress)showReturning();else showSelection();});
translate();if(progress)showReturning();else showSelection();
})();
