'use strict';
(()=>{
 const KEY='hudhud-plant-chapter-v1',ORDER=['water','sun','soil','needs'];
 const T={
 ar:{chapter:'ركن النبتة',garden:'الحديقة',seed:'من بذرة إلى زهرة',water:'اسقِ النبتة',sun:'دع الشمس تصل',soil:'ازرع البذرة',needs:'ماذا تحتاج النبتة؟',continue:'تابع الاكتشاف',next:'التالي',again:'مرة أخرى',back:'العودة إلى الحديقة',menu:'أنشطة النبتة',sunHint:'أبعد الغيمة عن الشمس',sunDone:'ضوء الشمس يساعد النبتة على النمو',soilHint:'ضع البذرة في التربة',soilTap:'المس التربة',soilWrong:'نزرع في التربة',soilDone:'في التربة تمتد الجذور',needsHint:'اختر ما يساعد النبتة على النمو',needsWrong:'هذه للّعب. جرّب شيئاً آخر',needsDone:'ماء، وضوء شمس، وتربة',finish:'أكملت ركن النبتة',message:'الله خلق النبات، ونحن نعتني به.',loading:'لحظة…',retry:'أعد المحاولة',save:'تعذّر حفظ التقدم على هذا الجهاز',cloud:'الغيمة',sunName:'ضوء الشمس',seedName:'البذرة',soilName:'التربة',paving:'البلاط',waterName:'الماء',ball:'الكرة',done:'مكتمل'},
 de:{chapter:'Die Pflanzenecke',garden:'Garten',seed:'Vom Samen zur Blüte',water:'Pflanze gießen',sun:'Lass die Sonne durch',soil:'Pflanze den Samen',needs:'Was braucht die Pflanze?',continue:'Weiter entdecken',next:'Weiter',again:'Noch einmal',back:'Zurück zum Garten',menu:'Pflanzenaktivitäten',sunHint:'Schiebe die Wolke zur Seite',sunDone:'Sonnenlicht hilft der Pflanze beim Wachsen',soilHint:'Lege den Samen in die Erde',soilTap:'Berühre die Erde',soilWrong:'Wir pflanzen in Erde',soilDone:'In der Erde breiten sich Wurzeln aus',needsHint:'Wähle aus, was der Pflanze beim Wachsen hilft',needsWrong:'Das ist zum Spielen. Versuche etwas anderes',needsDone:'Wasser, Sonnenlicht und Erde',finish:'Pflanzenecke abgeschlossen',message:'Allah hat die Pflanzen erschaffen. Wir kümmern uns um sie.',loading:'Einen Moment…',retry:'Erneut versuchen',save:'Fortschritt kann auf diesem Gerät nicht gespeichert werden',cloud:'Wolke',sunName:'Sonnenlicht',seedName:'Samen',soilName:'Erde',paving:'Fliesen',waterName:'Wasser',ball:'Ball',done:'Geschafft'},
 en:{chapter:'Plant corner',garden:'Garden',seed:'From seed to flower',water:'Water the plant',sun:'Let the sunshine in',soil:'Plant the seed',needs:'What does the plant need?',continue:'Keep exploring',next:'Next',again:'Play again',back:'Back to the garden',menu:'Plant activities',sunHint:'Move the cloud away from the sun',sunDone:'Sunlight helps the plant grow',soilHint:'Put the seed in the soil',soilTap:'Touch the soil',soilWrong:'We plant in soil',soilDone:'Roots spread through the soil',needsHint:'Choose what helps the plant grow',needsWrong:'That is for playing. Try something else',needsDone:'Water, sunlight and soil',finish:'Plant corner complete',message:'Allah created plants. We care for them.',loading:'One moment…',retry:'Try again',save:'Progress could not be saved on this device',cloud:'Cloud',sunName:'Sunlight',seedName:'Seed',soilName:'Soil',paving:'Tiles',waterName:'Water',ball:'Ball',done:'Complete'}
 };
 let dlg,lang='ar',step='menu',state='idle',session=0,timer=0,chosen=new Set(),selected=false,completed=new Set(),storageOK=true,options={};
 const q=s=>dlg.querySelector(s),c=()=>T[lang];
 const sprite=(name)=>'<span class="pc-prop pc-'+name+'" aria-hidden="true"></span>';
 const plant=()=>'<div class="pc-plant" aria-hidden="true"><span class="pc-bud"></span><span class="pc-flower"></span></div>';
 function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');completed=new Set(v?.version===1&&Array.isArray(v.done)?v.done.filter(x=>ORDER.includes(x)):[]);}catch{completed=new Set();}if(options.watered)completed.add('water');}
 function record(id){completed.add(id);try{localStorage.setItem(KEY,JSON.stringify({version:1,done:[...completed]}));storageOK=true;}catch{storageOK=false;}if(id==='water')options.onWater?.();window.dispatchEvent(new Event('hudhud:plant-progress'));}
 function allDone(){return ORDER.every(x=>completed.has(x));}
 function ensure(){if(dlg)return;dlg=document.createElement('dialog');dlg.id='plant-chapter';dlg.className='world-dialog';dlg.setAttribute('aria-labelledby','pc-title');document.body.append(dlg);dlg.addEventListener('close',()=>{session++;clearTimeout(timer);});}
 function shell(title){ensure();session++;clearTimeout(timer);state='idle';selected=false;chosen=new Set();dlg.dataset.step=step;dlg.dataset.state=state;dlg.dir=lang==='ar'?'rtl':'ltr';dlg.lang=lang;dlg.innerHTML='<header class="pc-header"><h2 id="pc-title"></h2><button class="pc-back" type="button"></button></header><main class="pc-stage"></main><footer class="pc-footer"><p class="pc-status" role="status" aria-live="polite"></p><div class="pc-actions"><button class="pc-replay" type="button" hidden></button><button class="pc-next" type="button" hidden></button><button class="pc-retry" type="button" hidden></button></div><p class="pc-save" hidden></p></footer>';q('#pc-title').textContent=title;q('.pc-back').textContent=c().garden;q('.pc-back').onclick=()=>dlg.close();q('.pc-replay').textContent=c().again;q('.pc-replay').onclick=()=>start(step);q('.pc-next').textContent=c().next;q('.pc-next').onclick=next;q('.pc-retry').textContent=c().retry;q('.pc-retry').onclick=()=>start(step);if(!dlg.open)dlg.showModal();}
 function status(text){q('.pc-status').textContent=text;}
 async function assets(){const token=session;state='loading';dlg.dataset.state=state;status(c().loading);q('.pc-stage').inert=true;try{await Promise.all(['assets/watering/garden.png','assets/watering/sprites.png','assets/plant-chapter/props.png'].map(src=>{const img=new Image();img.src=src;return img.decode();}));if(token!==session||!dlg.open)return false;state='ready';dlg.dataset.state=state;q('.pc-stage').inert=false;return true;}catch{if(token===session&&dlg.open){state='error';status(c().retry);q('.pc-retry').hidden=false;}return false;}}
 function finish(text){state='complete';dlg.dataset.state=state;record(step);status(text);q('.pc-replay').hidden=false;q('.pc-next').hidden=false;q('.pc-save').hidden=storageOK;q('.pc-save').textContent=c().save;q('.pc-next').focus({preventScroll:true});}
 function next(){const index=ORDER.indexOf(step);if(index<ORDER.length-1)start(ORDER[index+1]);else if(allDone())summary();else menu();}
 function delayedFinish(text){state='growing';dlg.dataset.state=state;const token=session;timer=setTimeout(()=>{if(token===session&&dlg.open)finish(text);},matchMedia('(prefers-reduced-motion: reduce)').matches?100:1600);}
 function menu(){step='menu';shell(c().chapter);q('.pc-stage').innerHTML='<div class="pc-menu"></div>';const grid=q('.pc-menu');const ids=['seed',...ORDER];ids.forEach(id=>{const b=document.createElement('button');b.type='button';b.dataset.activity=id;b.textContent=c()[id]+((id==='seed'?options.seedDone:completed.has(id))?' ✓':'');b.onclick=()=>{if(id==='seed'){dlg.close();options.onSeed?.();}else start(id);};grid.append(b);});const pending=ORDER.find(x=>!completed.has(x));status(allDone()?c().finish:'');if(pending){q('.pc-next').hidden=false;q('.pc-next').textContent=c().continue;q('.pc-next').onclick=()=>start(pending);}else{q('.pc-next').hidden=false;q('.pc-next').textContent=c().back;q('.pc-next').onclick=()=>dlg.close();}}
 function summary(){step='summary';shell(c().finish);q('.pc-stage').innerHTML=plant()+'<div class="pc-earned" aria-hidden="true">'+sprite('sun')+sprite('soil')+'<span class="pc-drop"></span></div>';dlg.dataset.state='complete';status(c().message);q('.pc-next').hidden=false;q('.pc-next').textContent=c().back;q('.pc-next').onclick=()=>dlg.close();q('.pc-replay').hidden=false;q('.pc-replay').textContent=c().menu;q('.pc-replay').onclick=menu;}
 function bindDrag(button,onDrop){let drag=null,suppress=false;const click=button.onclick;button.onclick=e=>{if(suppress){suppress=false;return;}click?.(e);};button.onpointerdown=e=>{if(state!=='ready')return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};suppress=false;button.setPointerCapture(e.pointerId);};button.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>8)drag.moved=true;if(drag.moved)button.style.translate=dx+'px '+dy+'px';};button.onpointerup=e=>{if(!drag||e.pointerId!==drag.id)return;const moved=drag.moved;drag=null;button.style.translate='';if(moved){suppress=true;onDrop(e);}};button.onpointercancel=()=>{drag=null;button.style.translate='';};}
 async function start(id){if(!ORDER.includes(id))return;step=id;if(id==='water'){if(dlg?.open)dlg.close();window.HUDHUDWatering.open(lang,()=>record('water'),()=>start('sun'));return;}shell(c()[id]);
 if(id==='sun'){
 q('.pc-stage').innerHTML=plant()+'<div class="pc-sun-disc">'+sprite('sun')+'</div><button type="button" class="pc-cloud" aria-label="'+c().cloud+'"><span></span></button>';
 const reveal=()=>{if(state!=='ready')return;q('.pc-cloud').disabled=true;delayedFinish(c().sunDone);};q('.pc-cloud').onclick=reveal;bindDrag(q('.pc-cloud'),reveal);if(await assets())status(c().sunHint);
 }else if(id==='soil'){
 q('.pc-stage').innerHTML='<div class="pc-seed-result">'+plant()+'</div><button type="button" class="pc-seed-button" aria-label="'+c().seedName+'" aria-pressed="false">'+sprite('seed')+'</button><div class="pc-ground-options"><button type="button" class="pc-ground pc-soil-target" aria-label="'+c().soilName+'">'+sprite('soil')+'</button><button type="button" class="pc-ground pc-tiles" aria-label="'+c().paving+'"><span aria-hidden="true"></span></button></div>';
 const seed=q('.pc-seed-button'),soil=q('.pc-soil-target');const plantSeed=()=>{if(state!=='ready')return;seed.disabled=true;seed.setAttribute('aria-pressed','false');delayedFinish(c().soilDone);};seed.onclick=()=>{if(state!=='ready')return;selected=!selected;seed.setAttribute('aria-pressed',String(selected));status(selected?c().soilTap:c().soilHint);};soil.onclick=()=>{if(selected)plantSeed();};q('.pc-tiles').onclick=()=>{if(state==='ready')status(c().soilWrong);};bindDrag(seed,e=>{const r=soil.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)plantSeed();else status(c().soilWrong);});if(await assets())status(c().soilHint);
 }else{
 q('.pc-stage').innerHTML=plant()+'<div class="pc-choices"></div>';const grid=q('.pc-choices');['water','ball','sun','soil'].forEach(key=>{const b=document.createElement('button');b.type='button';b.dataset.choice=key;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label',c()[{water:'waterName',ball:'ball',sun:'sunName',soil:'soilName'}[key]]);b.innerHTML=key==='water'?'<span class="pc-drop" aria-hidden="true"></span>':sprite(key);b.onclick=()=>{if(state!=='ready'||chosen.has(key))return;if(key==='ball'){status(c().needsWrong);return;}chosen.add(key);b.setAttribute('aria-pressed','true');b.disabled=true;status(c()[{water:'waterName',sun:'sunName',soil:'soilName'}[key]]);if(chosen.size===3)finish(c().needsDone);};grid.append(b);});if(await assets())status(c().needsHint);
 }
 }
 function setup(language,opts){lang=T[language]?language:'en';options=opts||{};read();}
 window.HUDHUDPlantChapter={openMenu(language,opts){setup(language,opts);menu();},start(language,id,opts){setup(language,opts);start(id);},isComplete(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v?.version===1&&ORDER.every(x=>v.done?.includes(x));}catch{return false;}}};
})();
