'use strict';
const TEXT={
de:{title:'Allah hat alles erschaffen',demo:'Erste spielbare Testversion · 8–10 Jahre',start:'Den Garten betreten',intro:'Entdecke den Himmel, die Pflanzen und die Tiere.',task:'Besuche die drei Stationen',taskBody:'Die drei Zeichen gehören zum Himmel, zu den Pflanzen und zu den Tieren. Danach geht es zur Holzwerkstatt.',next:'Weiter',sky:'Himmel',plant:'Pflanzen',animals:'Tiere',craft:'Werkstatt',apply:'Zuordnen',finish:'Abschluss',skyTask:'Bewege den Zeitregler und entdecke alle vier Ansichten.',times:['Morgendämmerung','Tag','Sonnenuntergang','Nacht'],skyEnd:'Nacht und Tag, Sonne, Mond und Sterne gehören zu Allahs Zeichen und Geschöpfen.',plantTask:'Tippe die vier Wachstumsphasen in der richtigen Reihenfolge an.',plantEnd:'Allah hat die Pflanzen erschaffen und lässt sie wachsen.',animalTask:'Wähle ein Tier und dann seinen passenden Lebensraum.',animalEnd:'Allah hat die Tiere erschaffen und ihnen geeignete Lebensräume gegeben.',animalNames:['Fisch','Biene','Kaninchen'],homes:['Teich','Blumen','Bau und Wiese'],craftTask:'Baue einen Tisch: zuerst die Tischplatte, dann vier Beine und zwei Querstreben.',parts:['Tischplatte','Bein','Querstrebe'],craftEnd:'Allah hat den Menschen und die Bäume erschaffen. Der Mensch baut den Tisch aus Holz, das Allah erschaffen hat.',sort:'Wähle für jedes Bild die passende Gruppe.',bins:['Allah hat es erschaffen','Vom Menschen hergestellt'],clarify:'Der Mensch stellt Dinge aus Materialien her, die Allah erschaffen hat, und mit Fähigkeiten, die Allah ihm gegeben hat.',names:['Baum','Mensch','Kaninchen','Sonne','Tisch','Stuhl','Tasche','Haus'],good:'Richtig. Weiter geht’s!',retry:'Versuche es noch einmal.',hint:'Schau auf das hervorgehobene Ziel.',done:'Station abgeschlossen',complete:'Etappe abgeschlossen',reward:'Du erhältst eine Wissensfeder.',back:'Zur Einheit',unit:'Allah kennenlernen',unitBody:'Die erste Etappe ist abgeschlossen. Du kannst sie erneut spielen.',replay:'Erneut spielen',reset:'Fortschritt zurücksetzen',confirm:'Diese Testetappe wirklich neu starten?',saved:'Fortschritt wird auf diesem Gerät gespeichert',noSave:'Speichern ist in diesem Browser nicht verfügbar',step:'Schritt',of:'von',seedNames:['Samen','Keimling','Knospe','Blüte']},
en:{title:'Allah created everything',demo:'First playable test · Ages 8–10',start:'Enter the garden',intro:'Discover the sky, plants and animals.',task:'Visit the three stations',taskBody:'The three symbols represent the sky, plants and animals. Then visit the woodworking station.',next:'Continue',sky:'Sky',plant:'Plants',animals:'Animals',craft:'Woodwork',apply:'Sort',finish:'Finish',skyTask:'Move the time slider and discover all four views.',times:['Dawn','Day','Sunset','Night'],skyEnd:'Night and day, the sun, moon and stars are among Allah’s signs and creations.',plantTask:'Tap the four growth stages in the correct order.',plantEnd:'Allah created plants and made them grow.',animalTask:'Choose an animal, then its suitable habitat.',animalEnd:'Allah created animals and provided suitable habitats for them.',animalNames:['Fish','Bee','Rabbit'],homes:['Pond','Flowers','Burrow and meadow'],craftTask:'Build a table: first its top, then four legs and two support rails.',parts:['Tabletop','Leg','Support rail'],craftEnd:'Allah created people and trees. People made the table from wood that Allah created.',sort:'Choose the suitable group for each picture.',bins:['Allah created it','Made by people'],clarify:'People make things from materials Allah created, using abilities He gave them.',names:['Tree','Person','Rabbit','Sun','Table','Chair','Bag','House'],good:'Correct. Keep going!',retry:'Try again.',hint:'Look at the highlighted destination.',done:'Station complete',complete:'Level complete',reward:'You earned a knowledge feather.',back:'Return to unit',unit:'Knowing Allah',unitBody:'You completed the first level. You can play it again.',replay:'Play again',reset:'Reset progress',confirm:'Restart this test level?',saved:'Progress is saved on this device',noSave:'Saving is unavailable in this browser',step:'Step',of:'of',seedNames:['Seed','Sprout','Bud','Flower']},
ar:{title:'الله خالق كل شيء',demo:'نسخة اختبار أولى قابلة للعب · ٨–١٠ سنوات',start:'ادخل الحديقة',intro:'تجوّل في الحديقة واكتشف آيات الله ومخلوقاته.',task:'أكمل المحطات الثلاث',taskBody:'علامات السماء والنبات والحيوان تدل على المحطات. بعدها نذهب إلى ركن النجارة.',next:'متابعة',sky:'السماء',plant:'النبات',animals:'الحيوانات',craft:'النجارة',apply:'التصنيف',finish:'الإنجاز',skyTask:'حرّك شريط الوقت وشاهد ما يظهر في السماء.',times:['الفجر','النهار','الغروب','الليل'],skyEnd:'الليل والنهار والشمس والقمر والنجوم من آيات الله ومخلوقاته.',plantTask:'رتّب مراحل نمو النبتة بالضغط عليها بالترتيب الصحيح.',plantEnd:'الله خلق النبات وجعل له نموًّا.',animalTask:'اختر حيوانًا ثم المكان المناسب له.',animalEnd:'خلق الله الحيوانات وهيّأ لها ما يناسبها.',animalNames:['سمكة','نحلة','أرنب'],homes:['بركة','أزهار','جحر ومرج'],craftTask:'ركّب الطاولة: السطح أولًا، ثم أربع أرجل ودعامتان.',parts:['سطح الطاولة','رجل','دعامة'],craftEnd:'الله خلق الإنسان والشجر. والإنسان صنع الطاولة من الخشب الذي خلقه الله.',sort:'اختر المجموعة المناسبة لكل صورة.',bins:['خلق الله','صنع الإنسان'],clarify:'الإنسان يصنع من مواد خلقها الله، وبقدرة أعطاه الله إياها.',names:['شجرة','إنسان','أرنب','شمس','طاولة','كرسي','حقيبة','بيت'],good:'أحسنت، تابع!',retry:'جرّب مرة أخرى.',hint:'انتبه إلى الموضع المحدد.',done:'اكتملت المحطة',complete:'اكتملت المرحلة',reward:'حصلت على ريشة معرفة مضيئة.',back:'العودة إلى الوحدة',unit:'معرفة الله والتوحيد',unitBody:'أكملت المرحلة الأولى. يمكنك لعبها مرة أخرى.',replay:'إعادة اللعب',reset:'إعادة ضبط التقدم',confirm:'هل تريد بدء هذه المرحلة التجريبية من جديد؟',saved:'يُحفظ التقدم على هذا الجهاز',noSave:'الحفظ غير متاح في هذا المتصفح',step:'الخطوة',of:'من',seedNames:['بذرة','نبتة صغيرة','برعم','زهرة']}
};
const root='assets/stages/ST-AQ-01/';
const SHEETS={sky:['SKY',1774,887],plant:['PLANT',1536,1024],animals:['ANIMALS',1536,1024],craft:['CRAFT',1536,1024],rewards:['REWARDS',1536,1024]};
// Source rectangles display existing art without altering the image files.
const RECT={sky:[[46,106,391,315],[470,106,400,315],[903,106,403,315],[1340,106,392,315],[45,465,350,325]],plant:[[25,400,325,175],[355,320,375,260],[755,115,370,465],[1130,0,405,575]],animals:[[30,100,450,380],[530,90,445,400],[1070,0,450,525],[10,570,490,390],[560,550,405,410],[1015,560,510,410]],craft:[[30,5,365,345],[400,100,300,245],[690,110,340,255],[1050,25,465,325],[70,380,490,225],[595,370,110,230],[1070,405,365,80],[335,590,290,395],[810,615,630,395]],rewards:[[135,25,405,410],[575,25,405,410],[1015,25,405,410],[120,480,550,470],[930,415,425,575]]};
function art(sheet,index,label=''){let [name,w,h]=SHEETS[sheet],[x,y,cw,ch]=RECT[sheet][index];return `<div class="sprite" style="aspect-ratio:${cw}/${ch}"><img alt="${label}" src="${root}HUDHUD_ST_AQ01_${name}_SHEET_v001.png" style="width:${w/cw*100}%;height:${h/ch*100}%;left:${-x/cw*100}%;top:${-y/ch*100}%"></div>`}
let saved={},storageOK=true;try{saved=JSON.parse(localStorage.getItem('hudhud-aq01-v1')||'{}')}catch{storageOK=false}
if(!saved||typeof saved!=='object')saved={};
let lang=TEXT[saved.lang]?saved.lang:'de',step=Number.isInteger(saved.step)?Math.max(0,Math.min(8,saved.step)):0;
let state={},mistakes=0,sound=false,audioCtx;const panel=document.querySelector('#panel');
function t(k){return TEXT[lang][k]}function save(){try{localStorage.setItem('hudhud-aq01-v1',JSON.stringify({lang,step}))}catch{storageOK=false}document.querySelector('#status').textContent=t(storageOK?'saved':'noSave')}
function ping(){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(620,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(320,audioCtx.currentTime+.09);g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}catch{}}
function message(ok){let f=document.querySelector('.feedback');if(f)f.textContent=t(ok?'good':++mistakes>=2?'hint':'retry');if(ok){mistakes=0;ping()}}
function next(){step=Math.min(8,step+1);state={};mistakes=0;save();render()}
function end(text){return `<p class="feedback"></p><p>${text}</p><button class="primary" data-next>${t('next')}</button>`}
function buttonArt(sheet,i,label,attrs=''){return `<button class="card" ${attrs}>${art(sheet,i,label)}<span>${label}</span></button>`}
function render(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelector('#reset').textContent=t('reset');save();document.querySelector('#caption').textContent='';let pins=[['sky',2,20,21],['plant',3,74,26],['animals',4,80,69],['craft',5,19,62]];document.querySelector('#mapButtons').innerHTML=pins.map(([k,s,x,y])=>`<button class="pin ${step>s?'done':step===s?'current':'locked'}" style="left:${x}%;top:${y}%" ${step===s?'':'disabled'}>${step>s?'✓ ':''}${t(k)}</button>`).join('');let html=`<p class="prototype">${t('demo')} · ${t('step')} ${Math.min(step+1,8)} ${t('of')} 8</p>`;
if(step===0)html+=`<h1>${t('title')}</h1><p>${t('intro')}</p><button class="primary" data-next>${t('start')}</button>`;
if(step===1)html+=`<h2>${t('task')}</h2><p>${t('taskBody')}</p><div class="row">${['sky','plant','animals'].map((k,i)=>`<div class="card">${art('rewards',i,t(k))}${t(k)}</div>`).join('')}</div><button class="primary" data-next>${t('next')}</button>`;
if(step===2){state.time??=0;state.seen??=new Set([0]);html+=`<h2>${t('sky')}</h2><p>${t('skyTask')}</p><div class="sky" id="skyView">${art('sky',state.time)}</div><label for="time">${t('times')[state.time]}</label><input id="time" type="range" min="0" max="3" step="1" value="${state.time}"><p>${state.seen.size} / 4</p>${state.seen.size===4?end(t('skyEnd')):''}`}
if(step===3){state.order??=[];let order=[2,0,3,1];html+=`<h2>${t('plant')}</h2><p>${t('plantTask')}</p><div class="row">${order.map(i=>buttonArt('plant',i,t('seedNames')[i],`data-plant="${i}" ${state.order.includes(i)?'disabled':''}`)).join('')}</div><div class="slots">${[0,1,2,3].map(i=>`<div class="slot ${state.order.includes(i)?'filled':''}">${state.order.includes(i)?'✓':i+1}</div>`).join('')}</div>${state.order.length===4?end(t('plantEnd')):'<p class="feedback"></p>'}`}
if(step===4){state.matches??=[];html+=`<h2>${t('animals')}</h2><p>${t('animalTask')}</p><div class="row">${[0,1,2].map(i=>buttonArt('animals',i,t('animalNames')[i],`data-animal="${i}" ${state.matches.includes(i)?'disabled':''}`)).join('')}</div><div class="row">${[2,0,1].map(i=>buttonArt('animals',i+3,t('homes')[i],`data-home="${i}"`)).join('')}</div>${state.matches.length===3?end(t('animalEnd')):'<p class="feedback"></p>'}`}
if(step===5){state.parts??=0;html+=`<h2>${t('craft')}</h2><p>${t('craftTask')}</p><div class="row">${[0,1,2].map((i)=>buttonArt('craft',i+4,t('parts')[i],`data-part="${i}"`)).join('')}</div><div class="slots">${Array.from({length:7},(_,i)=>`<div class="slot ${i<state.parts?'filled':''}">${i<state.parts?'✓':i+1}</div>`).join('')}</div>${state.parts===7?`<div class="row">${[0,1,2,3].map(i=>`<div class="card">${art('craft',i)}</div>`).join('')}</div>${end(t('craftEnd'))}`:'<p class="feedback"></p>'}`}
if(step===6){state.sort??=0;let sequence=[0,4,1,5,2,6,3,7],n=sequence[state.sort];html+=`<h2>${t('apply')}</h2><p class="note">${t('clarify')}</p>`;if(state.sort===8)html+=end(t('title'));else{let images=[art('craft',0),'<img alt="" src="assets/characters/HUDHUD_CHARACTER_BOY_MASTER_v001.png" style="width:100%;height:180px;object-fit:contain">',art('animals',2),art('sky',4),art('craft',3),art('craft',7),art('craft',8),art('rewards',3)];html+=`<p>${t('sort')} ${state.sort+1} / 8</p><div class="card" style="margin:auto">${images[n]}${t('names')[n]}</div><div class="row bins">${t('bins').map((s,i)=>`<button data-bin="${i}">${s}</button>`).join('')}</div><p class="feedback"></p>`}}
if(step===7){state.tokens??=[];html+=`<h2>${t('finish')}</h2><div class="row">${[0,1,2].map(i=>buttonArt('rewards',i,t(['sky','plant','animals'][i]),`data-token="${i}" ${state.tokens.includes(i)?'disabled':''}`)).join('')}</div><div class="slots">${[0,1,2].map(i=>`<div class="slot ${state.tokens.includes(i)?'filled':''}">${state.tokens.includes(i)?'✓':''}</div>`).join('')}</div>`;if(state.tokens.length===3)html+=`<h2>${t('title')}</h2><p class="verse" lang="ar">اللَّهُ خَالِقُ كُلِّ شَيْءٍ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ وَكِيلٌ</p><p style="text-align:center">39:62</p><div class="reward">${art('rewards',4)}</div><p>${t('reward')}</p><button class="primary" data-next>${t('back')}</button>`}
if(step===8)html+=`<h2>${t('unit')}</h2><p>${t('unitBody')}</p><p>✓ ${t('title')}</p><button data-replay>${t('replay')}</button>`;
panel.innerHTML=html;if(state.selected!==undefined)panel.querySelector(`[data-animal="${state.selected}"]`)?.classList.add('selected');
}
panel.addEventListener('input',e=>{if(e.target.id==='time'){let focus=e.target;state.time=Number(focus.value);state.seen.add(state.time);render();document.querySelector('#time').focus()}});
panel.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-next'))return next();if(b.hasAttribute('data-replay'))return restart();if(b.dataset.plant!==undefined){let n=+b.dataset.plant;if(n===state.order.length){state.order.push(n);render();message(true)}else{message(false);if(mistakes>=2)panel.querySelector(`[data-plant="${state.order.length}"]`).classList.add('selected')}}if(b.dataset.animal!==undefined){state.selected=+b.dataset.animal;render()}if(b.dataset.home!==undefined){if(state.selected===undefined)return;let n=+b.dataset.home;if(n===state.selected){state.matches.push(n);delete state.selected;render();message(true)}else{message(false);if(mistakes>=2)panel.querySelector(`[data-home="${state.selected}"]`).classList.add('selected')}}if(b.dataset.part!==undefined&&state.parts<7){let wanted=state.parts===0?0:state.parts<5?1:2;if(+b.dataset.part===wanted){state.parts++;render();message(true)}else{message(false);if(mistakes>=2)panel.querySelector(`[data-part="${wanted}"]`).classList.add('selected')}}if(b.dataset.bin!==undefined){let n=[0,4,1,5,2,6,3,7][state.sort];if(+b.dataset.bin===(n<4?0:1)){state.sort++;render();message(true)}else{message(false);if(mistakes>=2)panel.querySelector(`[data-bin="${n<4?0:1}"]`).classList.add('selected')}}if(b.dataset.token!==undefined){state.tokens.push(+b.dataset.token);render();ping()}});
function restart(){step=0;state={};mistakes=0;save();render()}
document.querySelector('#reset').onclick=()=>{if(confirm(t('confirm')))restart()};document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;render()});document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'♪ ✓':'♪ ×';e.currentTarget.setAttribute('aria-pressed',sound);ping()};render();
